let data = [
    {
        "name": "Projects @ Palantir",
        "btnID": "9",
        "coverImage": "Project/palantir_projects.png",
        "innerImage": "Project/palantir_projects.png",
        "modalId": "9",
        "dateCompleted": "--- ; Started full-time on Dec 2019, interned Summer 2019 + Summer 2018",
        "partners": "Palantir Team",
        "skillsUsed": "Python, Java, Javascript, SQL + more",
        "paragraphs": ["At Palantir, I've worked on a variety of projects!", "Contact me to learn more about the various things I've done at Palantir (you can see some details on my resume)."],
        "link": ""
    },
    {
        "name": "OpenElections: Freeing Election Data",
        "btnID": "6",
        "coverImage": "Project/openelections_outer.jpg",
        "innerImage": "Project/openelections_inner.png",
        "modalId": "6",
        "dateCompleted": "December 15, 2019",
        "partners": "Maggie C., Kara A., Karen S.",
        "skillsUsed": "R, Shiny, Python, Pandas, Javascript, HTML/CSS",
        "paragraphs": ["Open Elections is an open-source political-party-independent project started by Derek Willis, an interactive developer at the New York Times, to provide clean and usable data from state and local elections to those who need it regardless of that persons data literacy.", "For this project, my team and I worked on parsing a subset of the OpenElection data. We created a paper detailing our process, a methods flowchart for others working on this project, and an R Shiny App visualizing the data we successfully parsed. We won third place in the 2019 Fall Undergraduate Statistics Research Project (USRESP) competition with the methods paper.", "See more about this project at its GitHub page:"],
        "link": "https://sds-capstone.github.io/openelections/index.html"
    },
    {
        "name": "Pencil Grip Development in Children",
        "btnID": "7",
        "coverImage": "Project/pencil_grip_outer.jpg",
        "innerImage": "Project/pencil_grip_inner.png",
        "modalId": "7",
        "dateCompleted": "December 15, 2019",
        "partners": "Nancy Canevari",
        "skillsUsed": "Research Design, Data Collection, Data Modeling, Statistics",
        "paragraphs": ["For this project, we designed a research project focused on exploring the factors that affect pencil grip development in children. The goal was to provide the teachers with insights on what may affect a child's pencil grip development and how they could promote \"good\" pencil grip", "We worked with three different classrooms of 1st and 2nd grade children. As part of this project, we developed fun activities that would allow us to observe the different factors that may affect pencil grip, and performed these activities with the children 3+ times a week.", "Contact me to learn more about this research project. Below is a link to an article from the school I worked with, which includes an interview I did on the project: "],
        "link": "https://sophia.smith.edu/labschool/2020/01/27/research-methods-in-education-a-new-course-fosters-collaboration-at-campus-school/"
    },
    {
        "name": "TA Hours Queue",
        "btnID": "5",
        "coverImage": "Project/ta_hours_queue_outer.jpg",
        "innerImage": "Project/ta_hours_queue_inner.jpg",
        "modalId": "5",
        "dateCompleted": "December 15, 2019",
        "partners": "None",
        "skillsUsed": "Node.js, SQL, Javascript, HTML/CSS, Design",
        "paragraphs": ["A website with queue functionalities to help teaching assistants (TAs) during their teaching assistant hours. This project was built with the intention to serve the Smith College Computer Science department, based on the needs I identified during my time as teaching assistant. This is a personal project done with guidance from Professor Foley as a special studies course in my final semester (Fall 2019). It is not officially associated with the Smith College Computer Science department. Please feel free to adapt this project to your own needs (with due credit where necessary), and contact me with any questions.", "Learn more about the TA hours queue on my github: "],
        "link": "https://github.com/tiffanyxiao/ta-hours-queue"
    },
    {
        "name": "Modeling Child Congition",
        "btnID": "1",
        "coverImage": "Project/modeling_child_cognition.jpg",
        "innerImage": "Project/modeling_child_cognition2.png",
        "modalId": "1",
        "dateCompleted": "April 22, 2019",
        "partners": "Professor Peter De Villiers",
        "skillsUsed": "R, Multiple Rgression",
        "paragraphs": ["For this project, I worked with Professor Peter De Villiers to build models for exploring Theory of Mind differences between monolingual and bilingual children.", "Children grow in a variety of environments with different factors that can affect their development. From socioeconomic factors to bilingualism, there is interest on how these factors can affect a child’s development. In particular, there has been much research focused on the development of children’s Theory of Mind (ToM), or how a child is able to understand their own and others’ minds. In this project, we explored the potential impacts of factors such as language and executive functioning performance in children’s development. Specifically, we sought to analyze the question: What is the role of executive functioning and language skills in theory of mind performance in bilingual versus monolingual children?", "Contact me for the research paper."],
        "link": ""
    },
    {
        "name": "Predicting Billionaires' Networth",
        "btnID": "8",
        "coverImage": "Project/predicting_billionaires_networth_outer.jpg",
        "innerImage": "Project/predicting_billionaires_networth_inner.png",
        "modalId": "8",
        "dateCompleted": "May 15, 2018",
        "partners": "Audrey Jiang, Emma Ning",
        "skillsUsed": "Statistics, Multiple Regression",
        "paragraphs": ["For this project, we used different multiple regression models to attempt to best model the factors that affect a billionaire's networth. We sought to answer the following question: ", "Are age, number of source of wealth, type of industry, region, gender and type of wealth of a billionaire significantly associated with his or her net worth? If so, how do they influence the networth (positive or negative effect)?", "Contact me for the research paper." ],
        "link": ""
    },
    {
        "name": "GenNow: A Simple Website Generator",
        "btnID": "2",
        "coverImage": "Project/gennow.jpg",
        "innerImage": "Project/gennow2.jpg",
        "modalId": "2",
        "dateCompleted": "May 8, 2018",
        "partners": "Khadidja Fares",
        "skillsUsed": "Javascript, HTML/CSS, Design",
        "paragraphs": ["GenNow was built with the purpose of helping non-profit organizations be able to quickly and easily generate static websites to display their organization's information.", "Contact me if you'd like to see our final paper on this project.", "GENerate your website NOW at"],
        "link": "https://tiffanyxiao.com/nonprofit-website-generator/index.html"
    },
    {
        "name": "Predicting Airbnb Superhost Status",
        "btnID": "3",
        "coverImage": "Project/wordcloud.png",
        "innerImage": "Project/airbnb_poster.png",
        "modalId": "3",
        "dateCompleted": "December 15, 2017",
        "partners": "Shirley Xu",
        "skillsUsed": "R, Machine Learning, Design",
        "paragraphs": ["The objective of this project is to attempt to find the factors that can best predict whether a host is a superhost on Airbnb.", "We utilized two modeling techniques - logistic regression and classification tree. The logistic regression model correctly predicted superhost status 70.66% of the time on the test set, with a sensitivity value of 0.6748 and a specificity value of 0.7395. The classification tree correctly predicted superhost status 83.87% of the time on the test set, with the 3 predictor variables used in the tree construction are `number_of_reviews`, `host_total_listings_count`, and `review_scores_rating`.", "Both modeling techniques identified `number_of_reviews` and `review_scores_rating` as the most significant predictors in predicting whether or not a host is a superhost. Thus, the most reliable way to predict superhost status is most likely by finding out how many 5-star reviews a host has.", "Link to download the academic poster we presented"],
        "link": "Project/airbnb_poster.pdf"
    },
    {
        "name": "Facebook or FAKEbook: Statistics Project",
        "btnID": "12",
        "coverImage": "Project/facebook_outer.png",
        "innerImage": "Project/facebook_inner.png",
        "modalId": "12",
        "dateCompleted": "December 12, 2017",
        "partners": "Lauryn Aliwalas, Xela Miller",
        "skillsUsed": "R, Multiple Regression, Statistics",
        "paragraphs": ["In an era where fake news can gain a massive amount of popularity through social media websites such as Facebook, its important to critically analyze how these news posts gain popularity. For this project, we sought to examine news posts on Facebook and the factors that potentially led to their popularity.", "Specifically, we wanted to answer: \"For a news post on Facebook, does its factual rating, post type, number of comments, and/or political category have any influence on the frequency of shares this post gets?\"", "To answer this question, we searched for the best model that accurately predicted the frequency of shares on a post.", "Contact me for more information."],
        "link": ""
    },
    {
        "name": "A Data Analyst's Guide to Pokemon",
        "btnID": "11",
        "coverImage": "Project/pokemon_outer.png",
        "innerImage": "Project/pokemon_inner.png",
        "modalId": "11",
        "dateCompleted": "May 19, 2017",
        "partners": "Juliana Mishkin",
        "skillsUsed": "R, Python, HTML/CSS, Adobe Illustrator+Photoshop",
        "paragraphs": ["For this project, we wanted to create a fun visualization using a publicly available dataset.", "We chose to use a Pokemon dataset from Kaggle (https://www.kaggle.com/rounakbanik/pokemon). From this dataset, we built numerous R visualizations and accompanying programs to analyze the Pokemon data. For example, we created an R program that takes two Pokemon as inputs and compares their stats.", "You can use these analyses to become the best trainer there ever was :)","See the full visualization at the below link, and contact me for more information:"],
        "link": "Project/pokemon_full.png"
    },
    {
        "name": "True Stories of Dr. Seuss",
        "btnID": "4",
        "coverImage": "Project/drseuss.jpg",
        "innerImage": "Project/lorax_and_tiff.JPG",
        "modalId": "4",
        "dateCompleted": "December 12, 2016",
        "partners": "None",
        "skillsUsed": "Adobe Premiere + Photoshop + Illustrator",
        "paragraphs": ["As part of one of my academic final projects, I was told to write a paper on anything I discovered in the town of my college (Northampton, MA).", "For this topic, I chose to write about a Dr. Seuss exhibit I found in the town's local museum. Dr. Seuss's hometown is Springfield, MA, which is less than 10 minutes away from Northampton.", "Contact me for the full research paper", "As part of the project, I also created a youtube video summarizing my findings. You can find the youtube video at"],
        "link": "https://www.youtube.com/watch?v=9fD3JglPQXs"
    },
    {
        "name": "High Schoolers in Computer Science",
        "btnID": "10",
        "coverImage": "Project/high_school_cs_outer.png",
        "innerImage": "Project/high_school_cs_inner.png",
        "modalId": "10",
        "dateCompleted": "December 10, 2016",
        "partners": "None",
        "skillsUsed": "Tableau, Data Visualization, Statistics, Data Cleaning, Python",
        "paragraphs": ["As a female person of color in computer science, I care deeply about making sure that minority groups are welcomed and included in the industry. One of the ways to get more people involved in computer science is to introduce it to them at a young age. For this project, I wanted to explore the demographic of the students who take AP Computer Science in high school and see if I could identify any trends.", "I created a research paper with a number of interactive visualizations based on national 2016 data related to the AP Computer Science exams.", "Contact me for more information."],
        "link": ""
    },
    // {
    //     "name": "Name",
    //     "btnID": "1",
    //     "coverImage": "image.jpg",
    //     "innerImage": "image2.jpg",
    //     "modalId": "1",
    //     "dateCompleted": "Month Date, Year",
    //     "partners": "PartnerName",
    //     "skillsUsed": "Javascript",
    //     "paragraphs": ["para1", "para2", "para3"],
    //     "link": ""
    // },
];